version: "3.9"
services:
  backend:
    image: icyrockton/bgnodejs
    container_name: bgnodejs
    ports:
      - "3010:3010"
    networks:
      - backendnetwork
      - frontendnetwork
    depends_on:
      - mysqlDB
  mysqlDB:
    image: mysql
    container_name: bgmysql
    volumes:
    - ./mysql/swjtu.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: swjtucs!!!
      MYSQL_DATABASE: swjtucs
    expose:
      - 3306
    networks:
      - backendnetwork
  webSite:
    image: icyrockton/swjtu-website
    container_name: website
    ports:
    - "3000:80"
    networks:
      - frontendnetwork

networks:
  backendnetwork :
  frontendnetwork :


